-- Tables
CREATE TABLE COLOR (
    ID SERIAL PRIMARY KEY,
    COLOR_NAME VARCHAR(50) NOT NULL,
    COLOR_HEX VARCHAR(6) NOT NULL
);

CREATE TABLE DASH_CAM (
    ID SERIAL PRIMARY KEY,
    DASH_CAM_NAME VARCHAR(50) NOT NULL,
    TIME_LOCATION_X_MIN INT NULL,
    TIME_LOCATION_X_MAX INT NULL,
    TIME_LOCATION_Y_MIN INT NULL,
    TIME_LOCATION_Y_MAX INT NULL,
    GPS_LOCATION_X_MIN INT NULL,
    GPS_LOCATION_X_MAX INT NULL,
    GPS_LOCATION_Y_MIN INT NULL,
    GPS_LOCATION_Y_MAX INT NULL,
    SPEED_LOCATION_X_MIN INT NULL,
    SPEED_LOCATION_X_MAX INT NULL,
    SPEED_LOCATION_Y_MIN INT NULL,
    SPEED_LOCATION_Y_MAX INT NULL
);

CREATE TABLE VEHICLE (
    ID SERIAL PRIMARY KEY,
    MAKE VARCHAR(50) NOT NULL,
    MODEL VARCHAR(50) NOT NULL,
    VEHICLE_YEAR INT NOT NULL,
    COLOR_ID INT NOT NULL,
    DASH_CAM_ID INT NOT NULL,
    FOREIGN KEY (COLOR_ID) REFERENCES COLOR(ID),
    FOREIGN KEY (DASH_CAM_ID) REFERENCES DASH_CAM(ID)
);

CREATE TABLE TRIP (
    ID SERIAL PRIMARY KEY,
    VEHICLE_ID INT NOT NULL,
    START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP NOT NULL,
    FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE(ID)
);

CREATE TABLE VIDEO (
    ID SERIAL PRIMARY KEY,
    TRIP_ID INT NOT NULL,
    FILE_PATH VARCHAR(255) NOT NULL,
    FOREIGN KEY (TRIP_ID) REFERENCES TRIP(ID)
);

CREATE TABLE TRIP_DATA (
    ID SERIAL PRIMARY KEY,
    TRIP_ID INT NOT NULL,
    TRIP_DATA_TIME TIMESTAMP NOT NULL,
    LATITUDE VARCHAR NOT NULL,
    LONGITUDE VARCHAR NOT NULL,
    SPEED FLOAT NOT NULL,
    FOREIGN KEY (TRIP_ID) REFERENCES TRIP(ID)
);

CREATE TABLE CLIP (
    ID SERIAL PRIMARY KEY,
    IS_VIDEO BOOLEAN NOT NULL DEFAULT TRUE,
    FILE_PATH VARCHAR(255) NOT NULL  
);

CREATE TABLE EVENT_TYPE (
    ID SERIAL PRIMARY KEY,
    EVENT_TYPE_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE EVENT (
    ID SERIAL PRIMARY KEY,
    TRIP_ID INT NOT NULL,
    EVENT_TYPE VARCHAR(50) NOT NULL,
    EVENT_DATA VARCHAR(255) NOT NULL,
    USER_CONFIRMED BOOLEAN NOT NULL DEFAULT FALSE,
    COMMENT VARCHAR(255) NULL,
    START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP NOT NULL,
    CLIP_ID INT NULL,
    FOREIGN KEY (TRIP_ID) REFERENCES TRIP(ID),
    FOREIGN KEY (CLIP_ID) REFERENCES CLIP(ID)
);

CREATE TABLE LICENSE_PLATE (
    ID SERIAL PRIMARY KEY,
    LICENSE_PLATE_NUMBER VARCHAR(10) NOT NULL,
    DESCRIPTION VARCHAR(255) NULL
);

CREATE TABLE EVENT_LICENSE_PLATE (
    EVENT_ID INT NOT NULL,
    LICENSE_PLATE_ID INT NOT NULL,
    FOREIGN KEY (EVENT_ID) REFERENCES EVENT(ID),
    FOREIGN KEY (LICENSE_PLATE_ID) REFERENCES LICENSE_PLATE(ID)
);