name: Setup Database and Test Connection

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Navigate to src directory
      run: cd src
    - name: 'Create env file'
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env
    - name: Docker compose
      run: docker-compose up -d
    - name: Wait for 5 seconds
      run: sleep 5
    - name: Create Docker network
      run: docker network create --driver bridge mynetwork
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Navigate to src directory
      run: cd src
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest psycopg2
    - name: 'Create env file'
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env
    - name: Run Database Tests
      run: pytest tests/test_db.py
