name: Testing Application

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  database:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Docker compose
      run: |
        cd src
        docker-compose --verbose up -d
    - name: Sleep
      run: sleep 5
    - name: List Logs
      run: docker-compose logs
    - name: List running containers
      run: docker ps

