name: Testing Application

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  database:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Docker compose
      run: docker-compose up -d -f src/docker-compose.yml
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest psycopg2
    - name: Run Database Tests
      run: pytest src/tests/test_db.py
