name: Testing Application

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest psycopg2 opencv-python easyocr moviepy
    - name: Docker compose
      run: |
        cd src
        docker-compose up -d
    - name: Sleep
      run: sleep 5
    - name: Run Tests
      run: |
        cd src
        python3 -m pytest
